#!/bin/bash
#Shell script to initialize any Mac - January 2020
echo "Script has started"

#install homebrew
echo "Installing home-brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install curl
brew install curl

#install npm
brew install node

#install chrome
echo "installing google chrome"
brew cask install google-chrome

#install php storm
echo "installing php storm"
brew cask install phpstorm

#install VSCode
echo "installing VS code"
brew cask install visual-studio-code

#install source tree
echo "installing source tree"
brew cask install sourcetree

#install git 
echo "installing git "
brew install git

#install virtualbox
echo "installing virtualbox"
brew cask install virtualbox


#install Oh-my-zsh
echo "installing Oh-my-Zsh"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


#install sublime 
echo "installing sublime text editor"
brew cask install sublime-text

#install mumble
echo "installing mumble"
brew cask install mumble

#install brackets
echo "installing brackets"
brew cask install brackets

exit 0

